/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import {useFrame} from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
  }
  materials: {
    earth: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Earth.glb') as GLTFResult
  useFrame(() => { //rotates planet around sun
    group!.current!.rotation.y += .027;
   })
   return (
     <group ref={group} {...props} dispose={null}>
       <mesh geometry={nodes.Cube001.geometry} material={materials.earth} material-color='skyblue' position = {[12,0,0]} scale ={.0013}  />
     </group>
   )
}

