/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    cubemap: THREE.Mesh
  }
  materials: {
    jupiter: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Jupiter.glb') as GLTFResult
  useFrame(() => { //rotates planet around sun
    group!.current!.rotation.y += .021;
   })
   return (
     <group ref={group} {...props} dispose={null}>
       <mesh geometry={nodes.cubemap.geometry} material={materials.jupiter} material-color="orange" visible position={[15.1,0,0]} rotation={[Math.PI/2,0,0]} scale={.0022}></mesh>
     </group>
   )
}
