/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import {useFrame} from '@react-three/fiber'
type GLTFResult = GLTF & {
  nodes: {
    Cube008: THREE.Mesh
  }
  materials: {
    ['Default OBJ.005']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Mars.glb') as GLTFResult
  useFrame(() => { //rotates planet around sun
    group!.current!.rotation.y += .019;
   })
   return (
     <group ref={group} {...props} dispose={null}>
       <mesh geometry={nodes.Cube008.geometry} material={materials['Default OBJ.005']}  position = {[13.5,0,0]} scale ={.0009}/>
     </group>
   )
}

useGLTF.preload('/Mars.glb')
