/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Saturn001: THREE.Mesh
    RingsTop: THREE.Mesh
    RingsBottom: THREE.Mesh
  }
  materials: {
    None: THREE.MeshStandardMaterial
    SaturnRings: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Saturn.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Saturn001.geometry} material={materials.None} />
      <mesh geometry={nodes.RingsTop.geometry} material={nodes.RingsTop.material} />
      <mesh geometry={nodes.RingsBottom.geometry} material={nodes.RingsBottom.material} />
    </group>
  )
}

useGLTF.preload('/Saturn.glb')
