/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    cylindrically_mapped_sphere: THREE.Mesh;
  };
  materials: {
    ["Default OBJ.001"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/Venus.glb") as GLTFResult;
  useFrame(() => {
    //rotates planet around sun
    group!.current!.rotation.y += 0.0031;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.cylindrically_mapped_sphere.geometry}
        material={materials["Default OBJ.001"]}
        position={[14.8, 0, 0]}
        scale={0.0027}
      />
    </group>
  );
}

useGLTF.preload("/Venus.glb");
